/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iraiders_wesee_WeSee */

#ifndef _Included_org_iraiders_wesee_WeSee
#define _Included_org_iraiders_wesee_WeSee
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iraiders_wesee_WeSee_FRAME_WIDTH
#define org_iraiders_wesee_WeSee_FRAME_WIDTH 640L
#undef org_iraiders_wesee_WeSee_FRAME_HEIGHT
#define org_iraiders_wesee_WeSee_FRAME_HEIGHT 480L
#undef org_iraiders_wesee_WeSee_MINIMUM_CONTOUR_AREA
#define org_iraiders_wesee_WeSee_MINIMUM_CONTOUR_AREA 500L
#undef org_iraiders_wesee_WeSee_MINIMUM_CONTOUR_BB_WIDTH
#define org_iraiders_wesee_WeSee_MINIMUM_CONTOUR_BB_WIDTH 15L
#undef org_iraiders_wesee_WeSee_MANUAL_EXPOSURE
#define org_iraiders_wesee_WeSee_MANUAL_EXPOSURE 0.25
/*
 * Class:     org_iraiders_wesee_WeSee
 * Method:    setWhitebalance
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_iraiders_wesee_WeSee_setWhitebalance
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
